#!/usr/bin/env bash
# Installs and setup haproxy

apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.7
apt-get -y update
apt-get install -y haproxy=2.7.\*

echo "ENABLED=1" > /etc/default/haproxy

# Listen to web1 and web2 servers
echo "
   listen load_balancer
   bind *:80
   mode http
   balance roundrobin
   option httpclose
   option forwardfor
   server 185734-web-01 18.204.5.39:80 check
   server 185734-web-02 54.237.126.127:80 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start
